spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/elcentr-db
    username: postgres
    password: 1823
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
      driver-class-name: org.postgresql.Driver